// skuMap.js
// Auto-generated SKU mapping for Zoho Inventory integration
// Each product maps to its SKU and display name.

module.exports = {
  "Immune Shield Plus Capsules": { sku: "SKU-IMM-001", name: "Immune Shield Plus Capsules" },
  "SleepWell Naturals Capsules": { sku: "SKU-SLE-002", name: "SleepWell Naturals Capsules" },
  "Vital Energy Boost Capsules": { sku: "SKU-ENE-003", name: "Vital Energy Boost Capsules" },
  "Digestive Harmony Capsules": { sku: "SKU-DIG-004", name: "Digestive Harmony Capsules" },
  "HeartStrong Formula Capsules": { sku: "SKU-HEA-005", name: "HeartStrong Formula Capsules" },
  "MindSharp Memory Support Capsules": { sku: "SKU-BRA-006", name: "MindSharp Memory Support Capsules" },
  "JointFlex Advanced Capsules": { sku: "SKU-JOI-007", name: "JointFlex Advanced Capsules" },
  "Radiant Skin Complex Capsules": { sku: "SKU-SKI-008", name: "Radiant Skin Complex Capsules" },
  "Daily MultiMax Capsules": { sku: "SKU-GEN-009", name: "Daily MultiMax Capsules" },
  "StressEase Adaptogens Capsules": { sku: "SKU-STR-010", name: "StressEase Adaptogens Capsules" },
  "Probiotic 50 Billion Capsules": { sku: "SKU-DIG-011", name: "Probiotic 50 Billion Capsules" },
  "Liver Detox Cleanse Capsules": { sku: "SKU-DET-012", name: "Liver Detox Cleanse Capsules" },
  "Women’s Balance Formula Capsules": { sku: "SKU-WOM-013", name: "Women’s Balance Formula Capsules" },
  "Men’s Vitality Support Capsules": { sku: "SKU-MEN-014", name: "Men’s Vitality Support Capsules" },
  "Vision Protect Capsules": { sku: "SKU-EYE-015", name: "Vision Protect Capsules" },
  "Metabolism Mastery Capsules": { sku: "SKU-WEI-016", name: "Metabolism Mastery Capsules" },
  "Omega Supreme Gelcaps": { sku: "SKU-GEN-017", name: "Omega Supreme Gelcaps" },
  "Collagen Renew Capsules": { sku: "SKU-SKI-018", name: "Collagen Renew Capsules" },
  "Blood Sugar Balance Capsules": { sku: "SKU-MET-019", name: "Blood Sugar Balance Capsules" },
  "Thyroid Harmony Capsules": { sku: "SKU-HOR-020", name: "Thyroid Harmony Capsules" },
  "Adrenal Recharge Capsules": { sku: "SKU-STR-021", name: "Adrenal Recharge Capsules" },
  "Bone Strength Plus Capsules": { sku: "SKU-BON-022", name: "Bone Strength Plus Capsules" },
  "Kid’s Daily Multi Gummies": { sku: "SKU-KID-023", name: "Kid’s Daily Multi Gummies" },
  "Senior Vitality Capsules": { sku: "SKU-SEN-024", name: "Senior Vitality Capsules" },
  "Detox Greens Blend Powder": { sku: "SKU-DET-025", name: "Detox Greens Blend Powder" },
  "Sleep Calm Gummies": { sku: "SKU-SLE-026", name: "Sleep Calm Gummies" },
  "Healthy Hair Formula Capsules": { sku: "SKU-HAI-027", name: "Healthy Hair Formula Capsules" },
  "Men’s Prostate Care Capsules": { sku: "SKU-MEN-028", name: "Men’s Prostate Care Capsules" },
  "Anti-Inflammation Support Capsules": { sku: "SKU-INF-030", name: "Anti-Inflammation Support Capsules" },
  "Ailment / Condition": { sku: "SKU-CAT-031", name: "Ailment / Condition" },
  "Lung Health Support Capsules": { sku: "SKU-RES-032", name: "Lung Health Support Capsules" },
  "Circulation Plus Capsules": { sku: "SKU-HEA-033", name: "Circulation Plus Capsules" },
  "Detox Tea Blend Capsules": { sku: "SKU-DET-034", name: "Detox Tea Blend Capsules" },
  "Mood Lift Formula Capsules": { sku: "SKU-STR-035", name: "Mood Lift Formula Capsules" },
  "Antioxidant Max Capsules": { sku: "SKU-GEN-036", name: "Antioxidant Max Capsules" },
  "Skin Bright Complex Capsules": { sku: "SKU-SKI-037", name: "Skin Bright Complex Capsules" },
  "Men’s Performance Blend Capsules": { sku: "SKU-MEN-038", name: "Men’s Performance Blend Capsules" },
  "Women’s Energy Boost Capsules": { sku: "SKU-WOM-039", name: "Women’s Energy Boost Capsules" },
  "Kid’s Daily Gummies": { sku: "SKU-KID-040", name: "Kid’s Daily Gummies" },
  "Detox Superfoods Powder": { sku: "SKU-NAN-041", name: "Detox Superfoods Powder" },
  "Ailment / Condition": { sku: "SKU-CAT-042", name: "Ailment / Condition" },
  "Mood Lift Formula Capsules": { sku: "SKU-STR-043", name: "Mood Lift Formula Capsules" },
  "Antioxidant Max Capsules": { sku: "SKU-GEN-044", name: "Antioxidant Max Capsules" },
  "Skin Bright Complex Capsules": { sku: "SKU-SKI-045", name: "Skin Bright Complex Capsules" },
  "Men’s Performance Blend Capsules": { sku: "SKU-MEN-046", name: "Men’s Performance Blend Capsules" },
  "Women’s Energy Boost Capsules": { sku: "SKU-WOM-047", name: "Women’s Energy Boost Capsules" },
  "Kid’’s Daily Gummies": { sku: "SKU-KID-048", name: "Kid’’s Daily Gummies" },
  "Detox Superfoods Powder": { sku: "SKU-DET-049", name: "Detox Superfoods Powder" },
  "Healthy Aging Formula Capsules": { sku: "SKU-HEA-050", name: "Healthy Aging Formula Capsules" },
  "Gut Repair Formula Capsules": { sku: "SKU-GUT-051", name: "Gut Repair Formula Capsules" },
  "Women’s Hormone Harmony Capsules": { sku: "SKU-WOM-052", name: "Women’s Hormone Harmony Capsules" },
  "Ailment / Condition": { sku: "SKU-KEY-053", name: "Ailment / Condition" },
  "Kid’s Calm Gummies": { sku: "SKU-KID-054", name: "Kid’s Calm Gummies" },
  "Anti-Aging Complex Capsules": { sku: "SKU-HEA-055", name: "Anti-Aging Complex Capsules" },
  "Eye Defense Gummies": { sku: "SKU-EYE-056", name: "Eye Defense Gummies" },
  "Kid’s Growth Formula Capsules": { sku: "SKU-KID-057", name: "Kid’s Growth Formula Capsules" },
  "Detox Fiber Cleanse Capsules": { sku: "SKU-DET-058", name: "Detox Fiber Cleanse Capsules" },
  "Brain Youth Formula Capsules": { sku: "SKU-BRA-059", name: "Brain Youth Formula Capsules" },
  "Women’s Fertility Support Capsules": { sku: "SKU-WOM-060", name: "Women’s Fertility Support Capsules" },
  "Men’s Fertility Support Capsules": { sku: "SKU-MEN-061", name: "Men’s Fertility Support Capsules" },
  "Complete Wellness Pack Capsules": { sku: "SKU-GEN-062", name: "Complete Wellness Pack Capsules" },
  "Acai Berry Powder": { sku: "SKU-GEN-063", name: "Acai Berry Powder" },
  "Aloe Vera Capsules": { sku: "SKU-DIG-064", name: "Aloe Vera Capsules" },
  "Anti Aging Cream": { sku: "SKU-SKI-065", name: "Anti Aging Cream" },
  "Apple Cider Vinegar Capsules": { sku: "SKU-DIG-066", name: "Apple Cider Vinegar Capsules" },
  "Product Name": { sku: "SKU-CAT-067", name: "Product Name" },
  "BERBERINE Capsules": { sku: "SKU-GEN-068", name: "BERBERINE Capsules" },
  "GOLDENSEAL CAPSULES": { sku: "SKU-IMM-069", name: "GOLDENSEAL CAPSULES" },
  "COLLAGEN POWDER": { sku: "SKU-SKI-070", name: "COLLAGEN POWDER" },
  "L THEANINE Capsules": { sku: "SKU-STR-071", name: "L THEANINE Capsules" },
  "L ARGINIE GUMMIES": { sku: "SKU-MEN-072", name: "L ARGINIE GUMMIES" },
  "BIOTIN Capsules": { sku: "SKU-SKI-073", name: "BIOTIN Capsules" },
  "BCAA 5000 Capsules": { sku: "SKU-SPO-074", name: "BCAA 5000 Capsules" },
  "IODINE CAPSULES": { sku: "SKU-THY-075", name: "IODINE CAPSULES" },
  "POTASSIUM CAPSULES": { sku: "SKU-GEN-076", name: "POTASSIUM CAPSULES" },
  "TANTIVA CAPSULES": { sku: "SKU-MEN-077", name: "TANTIVA CAPSULES" },
  "Product Name": { sku: "SKU-KEY-078", name: "Product Name" },
  "Kid’s Calm Gummies": { sku: "SKU-KID-079", name: "Kid’s Calm Gummies" },
  "Anti-Aging Complex Capsules": { sku: "SKU-HEA-080", name: "Anti-Aging Complex Capsules" },
  "Eye Defense Gummies": { sku: "SKU-EYE-081", name: "Eye Defense Gummies" },
  "Kid’s Growth Formula Capsules": { sku: "SKU-KID-082", name: "Kid’s Growth Formula Capsules" },
  "Detox Fiber Cleanse Capsules": { sku: "SKU-DET-083", name: "Detox Fiber Cleanse Capsules" },
  "Brain Youth Formula Capsules": { sku: "SKU-BRA-084", name: "Brain Youth Formula Capsules" },
  "Women’s Fertility Support Capsules": { sku: "SKU-WOM-085", name: "Women’s Fertility Support Capsules" },
  "Men’s Fertility Support Capsules": { sku: "SKU-MEN-086", name: "Men’s Fertility Support Capsules" },
  "Complete Wellness Pack Capsules": { sku: "SKU-GEN-087", name: "Complete Wellness Pack Capsules" },
  "Acai Berry Powder": { sku: "SKU-GEN-088", name: "Acai Berry Powder" },
  "Aloe Vera Capsules": { sku: "SKU-DIG-089", name: "Aloe Vera Capsules" },
  "Product Name": { sku: "SKU-CAT-090", name: "Product Name" },
  "BETA SITOSTEROL Capsules": { sku: "SKU-MEN-091", name: "BETA SITOSTEROL Capsules" },
  "EXTENDIFY Capsules": { sku: "SKU-GEN-093", name: "EXTENDIFY Capsules" },
  "Men's Urinary Health Capsules": { sku: "SKU-MEN-094", name: "Men's Urinary Health Capsules" },
  "Pumpkin Seed Extract Capsules": { sku: "SKU-MEN-095", name: "Pumpkin Seed Extract Capsules" },
  "B3 NIACIN Capsules": { sku: "SKU-HEA-098", name: "B3 NIACIN Capsules" },
  "COLLOIDAL SILVER Liquid": { sku: "SKU-BRA-101", name: "COLLOIDAL SILVER Liquid" },
  "KRILL OIL Gelcaps": { sku: "SKU-HEA-102", name: "KRILL OIL Gelcaps" },
  "PHOSPHORUS Capsules": { sku: "SKU-NUT-104", name: "PHOSPHORUS Capsules" },
  "CDP CHOLINE Capsules": { sku: "SKU-BRA-105", name: "CDP CHOLINE Capsules" },
  "SAW PALMETTO Capsules": { sku: "SKU-MEN-106", name: "SAW PALMETTO Capsules" },
  "ASTRAGULUS Capsules": { sku: "SKU-IMM-110", name: "ASTRAGULUS Capsules" },
  "COLOSTRUM Capsules": { sku: "SKU-DIG-111", name: "COLOSTRUM Capsules" },
  "THYROID SUPPORT Capsules": { sku: "SKU-HOR-113", name: "THYROID SUPPORT Capsules" },
  "Magnesium Bisglycinate Capsules": { sku: "SKU-BRA-114", name: "Magnesium Bisglycinate Capsules" },
  "HYALURONIC ACID Capsules": { sku: "SKU-ANT-116", name: "HYALURONIC ACID Capsules" },
  "Ailment / Condition": { sku: "SKU-CAT-118", name: "Ailment / Condition" },
  "PROBIOTIC Capsules": { sku: "SKU-IMM-120", name: "PROBIOTIC Capsules" },
  "GARCINIA CAMBOGIA Capsules": { sku: "SKU-WEI-122", name: "GARCINIA CAMBOGIA Capsules" },
  "CHAMOMILE TEA CAPSULES": { sku: "SKU-STR-123", name: "CHAMOMILE TEA CAPSULES" },
  "Yohimbe Capsules": { sku: "SKU-MEN-124", name: "Yohimbe Capsules" },
  "Ailment / Condition": { sku: "SKU-CAT-125", name: "Ailment / Condition" },
  "GINKO BILOBA Capsules": { sku: "SKU-BRA-126", name: "GINKO BILOBA Capsules" },
  "Seamoss Capsules": { sku: "SKU-GEN-128", name: "Seamoss Capsules" },
  "CREATINE MONOHYDRATE Powder": { sku: "SKU-MEN-132", name: "CREATINE MONOHYDRATE Powder" },
  "GINGER Capsules": { sku: "SKU-ENE-133", name: "GINGER Capsules" },
  "BEE POLLEN Capsules": { sku: "SKU-RES-135", name: "BEE POLLEN Capsules" },
  "DEER ANTLER VELVET capsules": { sku: "SKU-MEN-136", name: "DEER ANTLER VELVET capsules" },
  "MITAKE MUSHROOM EXTRACT Capsules": { sku: "SKU-HEA-137", name: "MITAKE MUSHROOM EXTRACT Capsules" },
  "ANTI AGING CREAM": { sku: "SKU-SKI-138", name: "ANTI AGING CREAM" },
  "VITABEETS Powder": { sku: "SKU-HEA-140", name: "VITABEETS Powder" },
  "GLUCOSAMINE Capsules": { sku: "SKU-JOI-141", name: "GLUCOSAMINE Capsules" },
  "SAFFLOWER OIL CLA Capsules": { sku: "SKU-DIG-142", name: "SAFFLOWER OIL CLA Capsules" },
  "GREEN TEA EXTRACT CAPSULES": { sku: "SKU-BRA-143", name: "GREEN TEA EXTRACT CAPSULES" },
  "RESERVATROL Capsules": { sku: "SKU-HEA-144", name: "RESERVATROL Capsules" },
  "CBD GUMMIES": { sku: "SKU-GEN-146", name: "CBD GUMMIES" },
  "MORINGA LEAF Capsules": { sku: "SKU-DIA-147", name: "MORINGA LEAF Capsules" },
  "MIND OVER MATTER Capsules": { sku: "SKU-BRA-148", name: "MIND OVER MATTER Capsules" },
  "AMINO ACID COMPLEX Capsules": { sku: "SKU-MEN-150", name: "AMINO ACID COMPLEX Capsules" },
  "GREEN COFFEE BEAN CAPSULES": { sku: "SKU-WEI-151", name: "GREEN COFFEE BEAN CAPSULES" },
  "ACAI and Goji Powder": { sku: "SKU-IMM-152", name: "ACAI and Goji Powder" },
  "FOLIC ACID Capsules": { sku: "SKU-ENE-155", name: "FOLIC ACID Capsules" },
  "RASPBERRY KEYTONE CAPSULES": { sku: "SKU-MET-158", name: "RASPBERRY KEYTONE CAPSULES" },
  "MAGNESIUM TAURATE Capsules": { sku: "SKU-CAR-159", name: "MAGNESIUM TAURATE Capsules" },
  "CBD CREAM": { sku: "SKU-SKI-160", name: "CBD CREAM" },
  "NITRIC OXIDE CAPSULES": { sku: "SKU-HEA-161", name: "NITRIC OXIDE CAPSULES" },
  "MSM EYE DROPS": { sku: "SKU-VIS-162", name: "MSM EYE DROPS" },
  "ASHWAGANDHA CAPSULES": { sku: "SKU-STR-164", name: "ASHWAGANDHA CAPSULES" },
  "ASHWAGANDHA POWDER": { sku: "SKU-STR-165", name: "ASHWAGANDHA POWDER" },
  "CBD OIL": { sku: "SKU-STR-166", name: "CBD OIL" },
  "VITAGREENS SUPERFOOD POWDER": { sku: "SKU-GEN-168", name: "VITAGREENS SUPERFOOD POWDER" },
  "MULTIVITAMIN CAPSULES": { sku: "SKU-GEN-169", name: "MULTIVITAMIN CAPSULES" },
  "TURMERIC Capsules": { sku: "SKU-GEN-170", name: "TURMERIC Capsules" },
  "TULVIA TESTOSTERONE BOOSTER Capsules": { sku: "SKU-MEN-171", name: "TULVIA TESTOSTERONE BOOSTER Capsules" },
  "CoQ10 Capsules": { sku: "SKU-HEA-172", name: "CoQ10 Capsules" },
  "COLLAGEN PEPTIDES Capsules": { sku: "SKU-ANT-173", name: "COLLAGEN PEPTIDES Capsules" },
  "PHYTOPLANKTON POWDER ": { sku: "SKU-NUT-174", name: "PHYTOPLANKTON POWDER " },
  "IMMUNIFY CAPSULES": { sku: "SKU-IMM-175", name: "IMMUNIFY CAPSULES" },
  "ACAI BERRY CAPSULES": { sku: "SKU-INF-176", name: "ACAI BERRY CAPSULES" },
  "GINSENG CAPSULES": { sku: "SKU-ANT-177", name: "GINSENG CAPSULES" },
  "MARINE PHYTOPLANKTON Capsules": { sku: "SKU-NUT-179", name: "MARINE PHYTOPLANKTON Capsules" },
  "ARNICA CREAM": { sku: "SKU-SKI-180", name: "ARNICA CREAM" },
  "Vitamin D3 Capsules": { sku: "SKU-SKI-181", name: "Vitamin D3 Capsules" },
  "APPLE CIDER VINEGAR CAPSULES": { sku: "SKU-GEN-182", name: "APPLE CIDER VINEGAR CAPSULES" },
  "MAXX T CAPSULES": { sku: "SKU-MEN-183", name: "MAXX T CAPSULES" },
  "NERVEASE CREAM": { sku: "SKU-JOI-184", name: "NERVEASE CREAM" },
  "OsteoPlex": { sku: "SKU-JOI-185", name: "OsteoPlex" },
  "FlexiCollagen": { sku: "SKU-JOI-186", name: "FlexiCollagen" },
  "MSM Sulfur": { sku: "SKU-JOI-187", name: "MSM Sulfur" },
  "CoQ10 Liquid": { sku: "SKU-ENE-188", name: "CoQ10 Liquid" },
  "HGH": { sku: "SKU-ENE-189", name: "HGH" },
  "B12 Energy Boost": { sku: "SKU-ENE-190", name: "B12 Energy Boost" },
  "Omega-3 Fish Oil": { sku: "SKU-HEA-191", name: "Omega-3 Fish Oil" },
  "CardioGuard": { sku: "SKU-HEA-192", name: "CardioGuard" },
  "Hawthorn Extract": { sku: "SKU-HEA-193", name: "Hawthorn Extract" },
  "SleepWell Herbal Blend": { sku: "SKU-SLE-194", name: "SleepWell Herbal Blend" },
  "Melatonin Plus": { sku: "SKU-SLE-195", name: "Melatonin Plus" },
  "Valerian Root Complex": { sku: "SKU-SLE-196", name: "Valerian Root Complex" },
  "ImmuneShield": { sku: "SKU-IMM-197", name: "ImmuneShield" },
  "Vitamin C Plus Zinc": { sku: "SKU-IMM-198", name: "Vitamin C Plus Zinc" },
  "Elderberry Extract": { sku: "SKU-IMM-199", name: "Elderberry Extract" },
  "BrainBoost": { sku: "SKU-COG-200", name: "BrainBoost" },
  "Ginkgo Plus": { sku: "SKU-COG-201", name: "Ginkgo Plus" },
  "Lion’s Mane Mushroom": { sku: "SKU-COG-202", name: "Lion’s Mane Mushroom" },
  "ProBioMax": { sku: "SKU-DIG-203", name: "ProBioMax" },
  "Digestive Enzyme Blend": { sku: "SKU-DIG-204", name: "Digestive Enzyme Blend" },
  "Aloe Vera Complex": { sku: "SKU-DIG-205", name: "Aloe Vera Complex" },
  "CalmMind Ashwagandha": { sku: "SKU-STR-206", name: "CalmMind Ashwagandha" },
  "MoodLift St. John’s Wort": { sku: "SKU-STR-207", name: "MoodLift St. John’s Wort" },
  "Rhodiola Energy Calm": { sku: "SKU-STR-208", name: "Rhodiola Energy Calm" },
  "Collagen Beauty Plus": { sku: "SKU-BEA-209", name: "Collagen Beauty Plus" },
  "Skin Defense Antioxidant": { sku: "SKU-BEA-210", name: "Skin Defense Antioxidant" },
  "Hair & Nail Strength Blend": { sku: "SKU-BEA-211", name: "Hair & Nail Strength Blend" },
  "OsteoPlex Plus": { sku: "SKU-JOI-212", name: "OsteoPlex Plus" },
  "OsteoPlex Advanced": { sku: "SKU-JOI-213", name: "OsteoPlex Advanced" },
  "OsteoPlex Max": { sku: "SKU-JOI-214", name: "OsteoPlex Max" },
  "FlexiCollagen Plus": { sku: "SKU-JOI-215", name: "FlexiCollagen Plus" },
  "FlexiCollagen Advanced": { sku: "SKU-JOI-216", name: "FlexiCollagen Advanced" },
  "FlexiCollagen Max": { sku: "SKU-JOI-217", name: "FlexiCollagen Max" },
  "MSM Sulfur Plus": { sku: "SKU-JOI-218", name: "MSM Sulfur Plus" },
  "MSM Sulfur Advanced": { sku: "SKU-JOI-219", name: "MSM Sulfur Advanced" },
  "MSM Sulfur Max": { sku: "SKU-JOI-220", name: "MSM Sulfur Max" },
  "CoQ10 Plus": { sku: "SKU-ENE-221", name: "CoQ10 Plus" },
  "CoQ10 Advanced": { sku: "SKU-ENE-222", name: "CoQ10 Advanced" },
  "CoQ10 Max": { sku: "SKU-ENE-223", name: "CoQ10 Max" },
  "HGH Plus": { sku: "SKU-ENE-224", name: "HGH Plus" },
  "HGH Advanced": { sku: "SKU-ENE-225", name: "HGH Advanced" },
  "HGH Max": { sku: "SKU-ENE-226", name: "HGH Max" },
  "B12 Energy Boost Plus": { sku: "SKU-ENE-227", name: "B12 Energy Boost Plus" },
  "B12 Energy Boost Advanced": { sku: "SKU-ENE-228", name: "B12 Energy Boost Advanced" },
  "B12 Energy Boost Max": { sku: "SKU-ENE-229", name: "B12 Energy Boost Max" },
  "Omega-3 Fish Oil Plus": { sku: "SKU-HEA-230", name: "Omega-3 Fish Oil Plus" },
  "Omega-3 Fish Oil Advanced": { sku: "SKU-HEA-231", name: "Omega-3 Fish Oil Advanced" },
  "Omega-3 Fish Oil Max": { sku: "SKU-HEA-232", name: "Omega-3 Fish Oil Max" },
  "CardioGuard Plus": { sku: "SKU-HEA-233", name: "CardioGuard Plus" },
  "CardioGuard Advanced": { sku: "SKU-HEA-234", name: "CardioGuard Advanced" },
  "CardioGuard Max": { sku: "SKU-HEA-235", name: "CardioGuard Max" },
  "Hawthorn Extract Plus": { sku: "SKU-HEA-236", name: "Hawthorn Extract Plus" },
  "Hawthorn Extract Advanced": { sku: "SKU-HEA-237", name: "Hawthorn Extract Advanced" },
  "Hawthorn Extract Max": { sku: "SKU-HEA-238", name: "Hawthorn Extract Max" },
  "SleepWell Herbal Blend Plus": { sku: "SKU-SLE-239", name: "SleepWell Herbal Blend Plus" },
  "SleepWell Herbal Blend Advanced": { sku: "SKU-SLE-240", name: "SleepWell Herbal Blend Advanced" },
  "SleepWell Herbal Blend Max": { sku: "SKU-SLE-241", name: "SleepWell Herbal Blend Max" },
  "Melatonin Plus Plus": { sku: "SKU-SLE-242", name: "Melatonin Plus Plus" },
  "Melatonin Plus Advanced": { sku: "SKU-SLE-243", name: "Melatonin Plus Advanced" },
  "Melatonin Plus Max": { sku: "SKU-SLE-244", name: "Melatonin Plus Max" },
  "Valerian Root Complex Plus": { sku: "SKU-SLE-245", name: "Valerian Root Complex Plus" },
  "Valerian Root Complex Advanced": { sku: "SKU-SLE-246", name: "Valerian Root Complex Advanced" },
  "Valerian Root Complex Max": { sku: "SKU-SLE-247", name: "Valerian Root Complex Max" },
  "ImmuneShield Plus": { sku: "SKU-IMM-248", name: "ImmuneShield Plus" },
  "ImmuneShield Advanced": { sku: "SKU-IMM-249", name: "ImmuneShield Advanced" },
  "ImmuneShield Max": { sku: "SKU-IMM-250", name: "ImmuneShield Max" },
  "Vitamin C Plus Zinc Plus": { sku: "SKU-IMM-251", name: "Vitamin C Plus Zinc Plus" },
  "Vitamin C Plus Zinc Advanced": { sku: "SKU-IMM-252", name: "Vitamin C Plus Zinc Advanced" },
  "Vitamin C Plus Zinc Max": { sku: "SKU-IMM-253", name: "Vitamin C Plus Zinc Max" },
  "Elderberry Extract Plus": { sku: "SKU-IMM-254", name: "Elderberry Extract Plus" },
  "Elderberry Extract Advanced": { sku: "SKU-IMM-255", name: "Elderberry Extract Advanced" },
  "Elderberry Extract Max": { sku: "SKU-IMM-256", name: "Elderberry Extract Max" },
  "BrainBoost Plus": { sku: "SKU-COG-257", name: "BrainBoost Plus" },
  "BrainBoost Advanced": { sku: "SKU-COG-258", name: "BrainBoost Advanced" },
  "BrainBoost Max": { sku: "SKU-COG-259", name: "BrainBoost Max" },
  "Ginkgo Plus Plus": { sku: "SKU-COG-260", name: "Ginkgo Plus Plus" },
  "Ginkgo Plus Advanced": { sku: "SKU-COG-261", name: "Ginkgo Plus Advanced" },
  "Ginkgo Plus Max": { sku: "SKU-COG-262", name: "Ginkgo Plus Max" },
  "Lion’s Mane Mushroom Plus": { sku: "SKU-COG-263", name: "Lion’s Mane Mushroom Plus" },
  "Lion’s Mane Mushroom Advanced": { sku: "SKU-COG-264", name: "Lion’s Mane Mushroom Advanced" },
  "Lion’s Mane Mushroom Max": { sku: "SKU-COG-265", name: "Lion’s Mane Mushroom Max" },
  "ProBioMax Plus": { sku: "SKU-DIG-266", name: "ProBioMax Plus" },
  "ProBioMax Advanced": { sku: "SKU-DIG-267", name: "ProBioMax Advanced" },
  "ProBioMax Max": { sku: "SKU-DIG-268", name: "ProBioMax Max" },
  "Digestive Enzyme Blend Plus": { sku: "SKU-DIG-269", name: "Digestive Enzyme Blend Plus" },
  "Digestive Enzyme Blend Advanced": { sku: "SKU-DIG-270", name: "Digestive Enzyme Blend Advanced" },
  "Digestive Enzyme Blend Max": { sku: "SKU-DIG-271", name: "Digestive Enzyme Blend Max" },
  "Aloe Vera Complex Plus": { sku: "SKU-DIG-272", name: "Aloe Vera Complex Plus" },
  "Aloe Vera Complex Advanced": { sku: "SKU-DIG-273", name: "Aloe Vera Complex Advanced" },
  "Aloe Vera Complex Max": { sku: "SKU-DIG-274", name: "Aloe Vera Complex Max" },
  "CalmMind Ashwagandha Plus": { sku: "SKU-STR-275", name: "CalmMind Ashwagandha Plus" },
  "CalmMind Ashwagandha Advanced": { sku: "SKU-STR-276", name: "CalmMind Ashwagandha Advanced" },
  "CalmMind Ashwagandha Max": { sku: "SKU-STR-277", name: "CalmMind Ashwagandha Max" },
  "MoodLift St. John’s Wort Plus": { sku: "SKU-STR-278", name: "MoodLift St. John’s Wort Plus" },
  "MoodLift St. John’s Wort Advanced": { sku: "SKU-STR-279", name: "MoodLift St. John’s Wort Advanced" },
  "MoodLift St. John’s Wort Max": { sku: "SKU-STR-280", name: "MoodLift St. John’s Wort Max" },
  "Rhodiola Energy Calm Plus": { sku: "SKU-STR-281", name: "Rhodiola Energy Calm Plus" },
  "Rhodiola Energy Calm Advanced": { sku: "SKU-STR-282", name: "Rhodiola Energy Calm Advanced" },
  "Rhodiola Energy Calm Max": { sku: "SKU-STR-283", name: "Rhodiola Energy Calm Max" },
  "Collagen Beauty Plus Plus": { sku: "SKU-BEA-284", name: "Collagen Beauty Plus Plus" },
  "Collagen Beauty Plus Advanced": { sku: "SKU-BEA-285", name: "Collagen Beauty Plus Advanced" },
  "Collagen Beauty Plus Max": { sku: "SKU-BEA-286", name: "Collagen Beauty Plus Max" },
  "Skin Defense Antioxidant Plus": { sku: "SKU-BEA-287", name: "Skin Defense Antioxidant Plus" },
  "Skin Defense Antioxidant Advanced": { sku: "SKU-BEA-288", name: "Skin Defense Antioxidant Advanced" },
  "Skin Defense Antioxidant Max": { sku: "SKU-BEA-289", name: "Skin Defense Antioxidant Max" },
  "Hair & Nail Strength Blend Plus": { sku: "SKU-BEA-290", name: "Hair & Nail Strength Blend Plus" },
  "Hair & Nail Strength Blend Advanced": { sku: "SKU-BEA-291", name: "Hair & Nail Strength Blend Advanced" },
  "Hair & Nail Strength Blend Max": { sku: "SKU-BEA-292", name: "Hair & Nail Strength Blend Max" }
};
